#  The ROS remote project - ROS 2 Deployment Container
#  Copyright 2024 Samyar Sadat Akhavi
#  Prepared by Samyar Sadat Akhavi, 2024.
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <https: www.gnu.org/licenses/>.

services:
    ros_ws:
        build:
            dockerfile: Dockerfile
            context: ./
        container_name: ros_remote_ws
        restart: unless-stopped
        network_mode: host
        cap_add:
          - SYS_PTRACE
        security_opt:
          - "seccomp=unconfined"
        deploy:
            resources:
                reservations:
                    devices:
                      - driver: nvidia
                        count: 1
                        capabilities: [gpu]
        environment:
          - DISPLAY
        device_cgroup_rules:
          - "c *:* rmw"
        volumes:
          - type: bind
            source: ../
            target: /home/nonroot/ros_ws
          - type: bind
            source: ../../ros_robot_project/Source Code/ros_ws_robot/src/ros_robot_msgs
            target: /home/nonroot/ros_ws/src/ros_robot_msgs
          - type: bind
            source: ../../pico_ws/libmicroros/src/remote_pico_coms
            target: /home/nonroot/ros_ws/src/remote_pico_coms
          - /tmp/.X11-unix:/tmp/.X11-unix:rw
          - /dev:/dev