#  The ROS remote project - Raspberry Pi Pico Communication Messages Package
#  Set LED states.
#  Copyright 2024 Samyar Sadat Akhavi
#  Written by Samyar Sadat Akhavi, 2024.
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <https: www.gnu.org/licenses/>.


# 0: Solid PWM output, 1: Flashing PWM output (slow), 2: Fading to and from PWM output (slow), 
# 3: Flashing PWM output (fast), 4: Fading to and from PWM output (fast)
uint8[11] led_modes
uint16[11] pwm_outputs

# Array LED order:
# [right_kd2_led, right_green_led, right_blue_led, left_top_yellow_led,
# left_top_green_led, left_red_led, left_bottom_yellow_led, left_bottom_green_1_led,
# left_bottom_green_2_led, left_red_kd2_led, left_green_kd2_led]
bool[11] set_state_mask
---
bool success